#pragma once

#define GET_CURRENT_WORLD "get_current_world"
#define GET_AVAILABLE_WORLDS "get_available_worlds"   
#define LOAD_WORLD "load_world"
#define RELOAD_WORLD "reload_world"
#define GET_PROCEDURAL_LOCATIONS "get_procedural_locations"
#define SET_PROCEDURAL_LOCATION "set_procedural_location"
#define HOVER "hover"
#define TAKEOFF "takeoff"
#define LAND "land"
#define SET_REFERENCE_THRUST "set_reference_thrust"
#define SET_REFERENCE_RATE "set_reference_rate"
#define SET_REFERENCE_ATTITUDE "set_reference_attitude"
#define SET_REFERENCE_VELOCITY "set_reference_velocity"
#define SET_REFERENCE_POSITION "set_reference_position"
#define CANCEL_TASK "cancel_task"
#define GET_AVAILABLE_MISSIONS "get_available_missions"
#define LOAD_MISSION "load_mission"
#define LOAD_CUSTOM_MISSION "load_custom_mission"
#define START_FREE_FLIGHT "start_free_flight"
#define GET_MISSION_STATE "get_mission_state"
#define START_MISSION "start_mission"
#define RESTART_MISSION "restart_mission"
#define STOP_MISSION "stop_mission"
#define GET_AVAILABLE_CAMERAS "get_camera_names"
#define SET_CAMERA_SETTINGS "set_camera_settings"
#define GET_IMAGE "get_image"
#define GET_DRONE_STATE "get_drone_state"
#define GET_MISSION_INFO "get_mission_info"
#define GET_METRIC_RESULTS "get_metric_results"

